services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
      - "3001:8080"
    volumes:
      - ../webui.db:/app/backend/data/webui.db
    network_mode: "host"

networks:
  default:
    external:
      name: host
    driver: host
