services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    ports:
      - "8092:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./backup/excalidraw:/opt/node_app/app:delegated
      - ./backup/excalidraw/package.json:/opt/node_app/package.json
      - ./backup/excalidraw/yarn.lock:/opt/node_app/yarn.lock
      - ./backup/excalidraw/node_modules:/opt/node_app/app/node_modules
    networks:
      - open-webui

networks:
  open-webui:
    external: true