services:
  excalidraw:
    build:
      context: .
      dockerfile: excalidraw.Dockerfile
    container_name: excalidraw
    ports:
      - "4002:80"
    restart: on-failure
    stdin_open: true
    healthcheck:
      disable: true
    volumes:
      - ./backup/excalidraw:/opt/node_app/app:delegated
      - ./backup/excalidraw/package.json:/opt/node_app/package.json
      - ./backup/excalidraw/yarn.lock:/opt/node_app/yarn.lock
      - ./backup/excalidraw/node_modules:/opt/node_app/app/node_modules
    networks:
      - open-webui

networks:
  open-webui:
    external: true