services:
  open-webui:
    container_name: open-webui
    build: .
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
      - "3001:8080"
    volumes:
      - ./backup:/app/backend/data/
    networks:
      - open-webui

networks:
  open-webui:
    external: true
